import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const GITHUB_USERNAME = 'xuanyiying';
const OUTPUT_FILE = path.join(__dirname, '../src/data/projects.ts');
const REPO_API_URL = `https://api.github.com/users/${GITHUB_USERNAME}/repos`;
interface GitHubRepo {
    id: number;
    name: string;
    description: string | null;
    fork: boolean;
    html_url: string;
    homepage: string | null;
    stargazers_count: number;
    forks_count: number;
    updated_at: string;
    language: string | null;
    topics: string[];
}

async function fetchGithubProjects() {
    console.log(`Fetching repositories for ${GITHUB_USERNAME}...`);
    
    try {
        const response = await fetch(REPO_API_URL, {
            headers: {
                'Accept': 'application/vnd.github.v3+json',
                'User-Agent': 'Node.js-Fetch-Script'
            }
        });

        if (!response.ok) {
            throw new Error(`GitHub API error: ${response.status} ${response.statusText}`);
        }

        const repos = await response.json() as GitHubRepo[];
        
        // Filter out forks and map to our Project structure
        const projects = repos
            .filter((repo: GitHubRepo) => !repo.fork)
            .map((repo: GitHubRepo) => ({
                id: repo.id.toString(),
                title: repo.name,
                description: repo.description || 'No description provided.',
                longDescription: repo.description || 'No description provided.',
                image: `/images/projects/${repo.name.toLowerCase()}.jpg`, // Default image path
                tags: repo.topics && repo.topics.length > 0 ? repo.topics : (repo.language ? [repo.language] : []),
                github: repo.html_url,
                demo: repo.homepage || '',
                featured: repo.stargazers_count > 10, // Example logic for featured projects
                stars: repo.stargazers_count,
                forks: repo.forks_count,
                updatedAt: repo.updated_at.split('T')[0],
                language: repo.language || 'Unknown'
            }));

        const fileContent = `// This file is automatically generated by scripts/fetch-github-projects.mjs
// Do not edit this file manually.

export interface Project {
    id: string;
    title: string;
    description: string;
    longDescription: string;
    image: string;
    tags: string[];
    github: string;
    demo: string;
    featured: boolean;
    stars: number;
    forks: number;
    updatedAt: string;
    language: string;
}

export const projects: Project[] = ${JSON.stringify(projects, null, 4)};
`;

        fs.writeFileSync(OUTPUT_FILE, fileContent);
        console.log(`Successfully updated ${OUTPUT_FILE} with ${projects.length} projects.`);
        
    } catch (error: any) {
        console.error('Error fetching GitHub projects:', error.message);
        process.exit(1);
    }
}

fetchGithubProjects();
