// This file is automatically generated by scripts/fetch-github-projects.mjs
// Do not edit this file manually.

export interface Project {
    id: string;
    title: string;
    description: string;
    longDescription: string;
    image: string;
    tags: string[];
    github: string;
    demo: string;
    featured: boolean;
    stars: number;
    forks: number;
    updatedAt: string;
    language: string;
}

export const projects: Project[] = [
    {
        "id": "1123960731",
        "title": "ezento",
        "description": "No description provided.",
        "longDescription": "No description provided.",
        "image": "/images/projects/ezento.jpg",
        "tags": [
            "TypeScript"
        ],
        "github": "https://github.com/xuanyiying/ezento",
        "demo": "",
        "featured": false,
        "stars": 0,
        "forks": 0,
        "updatedAt": "2025-12-28",
        "language": "TypeScript"
    },
    {
        "id": "1123603049",
        "title": "cleanup-assistant",
        "description": "No description provided.",
        "longDescription": "No description provided.",
        "image": "/images/projects/cleanup-assistant.jpg",
        "tags": [
            "Go"
        ],
        "github": "https://github.com/xuanyiying/cleanup-assistant",
        "demo": "",
        "featured": false,
        "stars": 1,
        "forks": 0,
        "updatedAt": "2025-12-27",
        "language": "Go"
    },
    {
        "id": "1105497096",
        "title": "ai-ace-job",
        "description": "offer收割机，简历优化，面试指导，面试题预测",
        "longDescription": "offer收割机，简历优化，面试指导，面试题预测",
        "image": "/images/projects/ai-ace-job.jpg",
        "tags": [
            "TypeScript"
        ],
        "github": "https://github.com/xuanyiying/ai-ace-job",
        "demo": "",
        "featured": false,
        "stars": 0,
        "forks": 0,
        "updatedAt": "2025-12-23",
        "language": "TypeScript"
    },
    {
        "id": "1032539488",
        "title": "wedding",
        "description": "No description provided.",
        "longDescription": "No description provided.",
        "image": "/images/projects/wedding.jpg",
        "tags": [
            "TypeScript"
        ],
        "github": "https://github.com/xuanyiying/wedding",
        "demo": "",
        "featured": false,
        "stars": 0,
        "forks": 0,
        "updatedAt": "2025-09-28",
        "language": "TypeScript"
    },
    {
        "id": "791333569",
        "title": "publication-shop",
        "description": "No description provided.",
        "longDescription": "No description provided.",
        "image": "/images/projects/publication-shop.jpg",
        "tags": [
            "Go"
        ],
        "github": "https://github.com/xuanyiying/publication-shop",
        "demo": "",
        "featured": false,
        "stars": 0,
        "forks": 0,
        "updatedAt": "2024-05-08",
        "language": "Go"
    }
];
