// This file is automatically generated by scripts/fetch-github-projects.ts
// Do not edit this file manually.

export interface ProjectMetrics {
    codeQuality: number;
    apiDesign: number;
    deployment: number;
}

export interface FullStackArchitecture {
    frontend: string[];
    backend: string[];
    database: string[];
    devops: string[];
}

export interface Project {
    id: string;
    title: string;
    description: string;
    longDescription: string;
    image: string;
    images: string[];
    tags: string[];
    architecture: FullStackArchitecture;
    metrics: ProjectMetrics;
    github: string;
    demo: string;
    featured: boolean;
    stars: number;
    forks: number;
    updatedAt: string;
    language: string;
}

export const projectsEn: Project[] = [
    {
        "id": "1105497096",
        "image": "/images/projects/intervai.svg",
        "images": [
            "/images/projects/intervai.svg",
            "/images/projects/intervai.png"
        ],
        "github": "https://github.com/xuanyiying/IntervAI",
        "demo": "https://udefined.cc",
        "featured": true,
        "stars": 3,
        "forks": 0,
        "updatedAt": "2026-03-04",
        "language": "TypeScript",
        "tags": [
            "TypeScript",
            "interview-ai"
        ],
        "architecture": {
            "frontend": [
                "Parser",
                "TypeScript"
            ],
            "backend": [
                "Eslint-plugin"
            ],
            "database": [],
            "devops": [
                "Eslint",
                "Eslint-config-prettier",
                "Eslint-plugin-prettier",
                "Prettier"
            ]
        },
        "metrics": {
            "codeQuality": 85,
            "apiDesign": 93,
            "deployment": 91
        },
        "title": "IntervAI",
        "description": "Interview AI 是一站式智能求职辅助平台，聚焦简历优化与模拟面试闭环。系统通过多模型协作、结构化评估与可视化反馈，帮助候选人快速识别差距、提升表达质量并完成投递准备。",
        "longDescription": "Interview AI 是一站式智能求职辅助平台，聚焦简历优化与模拟面试闭环。系统通过多模型协作、结构化评估与可视化反馈，帮助候选人快速识别差距、提升表达质量并完成投递准备。"
    },
    {
        "id": "1123603049",
        "image": "/images/projects/cleanup-cli.svg",
        "images": [
            "/images/projects/cleanup-cli.svg",
            "/images/projects/cleanup-cli.png"
        ],
        "github": "https://github.com/xuanyiying/cleanup-cli",
        "demo": "",
        "featured": true,
        "stars": 1,
        "forks": 0,
        "updatedAt": "2026-01-19",
        "language": "Go",
        "tags": [
            "Go"
        ],
        "architecture": {
            "frontend": [
                "Cobra"
            ],
            "backend": [],
            "database": [],
            "devops": []
        },
        "metrics": {
            "codeQuality": 93,
            "apiDesign": 93,
            "deployment": 82
        },
        "title": "cleanup-cli",
        "description": "A full-stack application built with modern technologies.",
        "longDescription": "A full-stack application built with modern technologies."
    },
    {
        "id": "1123960731",
        "image": "/images/projects/ezento.svg",
        "images": [
            "/images/projects/ezento.svg",
            "/images/projects/ezento.png"
        ],
        "github": "https://github.com/xuanyiying/ezento",
        "demo": "",
        "featured": true,
        "stars": 1,
        "forks": 0,
        "updatedAt": "2025-12-30",
        "language": "TypeScript",
        "tags": [
            "TypeScript"
        ],
        "architecture": {
            "frontend": [],
            "backend": [],
            "database": [],
            "devops": []
        },
        "metrics": {
            "codeQuality": 93,
            "apiDesign": 83,
            "deployment": 88
        },
        "title": "ezento",
        "description": "A full-stack application built with modern technologies.",
        "longDescription": "A full-stack application built with modern technologies."
    },
    {
        "id": "1032539488",
        "image": "/images/projects/wedding.svg",
        "images": [
            "/images/projects/wedding.svg",
            "/images/projects/wedding.png"
        ],
        "github": "https://github.com/xuanyiying/wedding",
        "demo": "",
        "featured": false,
        "stars": 0,
        "forks": 0,
        "updatedAt": "2025-09-28",
        "language": "TypeScript",
        "tags": [
            "TypeScript"
        ],
        "architecture": {
            "frontend": [],
            "backend": [],
            "database": [],
            "devops": []
        },
        "metrics": {
            "codeQuality": 93,
            "apiDesign": 82,
            "deployment": 83
        },
        "title": "WedMaster",
        "description": "A full-stack application built with modern technologies.",
        "longDescription": "A full-stack application built with modern technologies."
    }
];

export const projectsZh: Project[] = [
    {
        "id": "1105497096",
        "image": "/images/projects/intervai.svg",
        "images": [
            "/images/projects/intervai.svg",
            "/images/projects/intervai.png"
        ],
        "github": "https://github.com/xuanyiying/IntervAI",
        "demo": "https://udefined.cc",
        "featured": true,
        "stars": 3,
        "forks": 0,
        "updatedAt": "2026-03-04",
        "language": "TypeScript",
        "tags": [
            "TypeScript",
            "interview-ai"
        ],
        "architecture": {
            "frontend": [
                "Parser",
                "TypeScript"
            ],
            "backend": [
                "Eslint-plugin"
            ],
            "database": [],
            "devops": [
                "Eslint",
                "Eslint-config-prettier",
                "Eslint-plugin-prettier",
                "Prettier"
            ]
        },
        "metrics": {
            "codeQuality": 85,
            "apiDesign": 93,
            "deployment": 91
        },
        "title": "IntervAI",
        "description": "人工智能相关项目",
        "longDescription": "人工智能相关项目"
    },
    {
        "id": "1123603049",
        "image": "/images/projects/cleanup-cli.svg",
        "images": [
            "/images/projects/cleanup-cli.svg",
            "/images/projects/cleanup-cli.png"
        ],
        "github": "https://github.com/xuanyiying/cleanup-cli",
        "demo": "",
        "featured": true,
        "stars": 1,
        "forks": 0,
        "updatedAt": "2026-01-19",
        "language": "Go",
        "tags": [
            "Go"
        ],
        "architecture": {
            "frontend": [
                "Cobra"
            ],
            "backend": [],
            "database": [],
            "devops": []
        },
        "metrics": {
            "codeQuality": 93,
            "apiDesign": 93,
            "deployment": 82
        },
        "title": "cleanup-cli",
        "description": "命令行工具",
        "longDescription": "命令行工具"
    },
    {
        "id": "1123960731",
        "image": "/images/projects/ezento.svg",
        "images": [
            "/images/projects/ezento.svg",
            "/images/projects/ezento.png"
        ],
        "github": "https://github.com/xuanyiying/ezento",
        "demo": "",
        "featured": true,
        "stars": 1,
        "forks": 0,
        "updatedAt": "2025-12-30",
        "language": "TypeScript",
        "tags": [
            "TypeScript"
        ],
        "architecture": {
            "frontend": [],
            "backend": [],
            "database": [],
            "devops": []
        },
        "metrics": {
            "codeQuality": 93,
            "apiDesign": 83,
            "deployment": 88
        },
        "title": "MedAI-Consultant",
        "description": "基于现代 AI 的全栈对话式应用，用于辅助医疗诊断，具有智能分型、预诊咨询和报告解读功能。",
        "longDescription": "MedAI-Consultant 是一个先进的医疗保健解决方案，利用大语言模型 (LLM) 自动化患者指导和临床数据解读。它具有智能分型算法、结构化的预诊工作流程以及基于 RAG 架构的高精度医疗报告分析功能。"
    },
    {
        "id": "1032539488",
        "image": "/images/projects/wedding.svg",
        "images": [
            "/images/projects/wedding.svg",
            "/images/projects/wedding.png"
        ],
        "github": "https://github.com/xuanyiying/wedding",
        "demo": "",
        "featured": false,
        "stars": 0,
        "forks": 0,
        "updatedAt": "2025-09-28",
        "language": "TypeScript",
        "tags": [
            "TypeScript"
        ],
        "architecture": {
            "frontend": [],
            "backend": [],
            "database": [],
            "devops": []
        },
        "metrics": {
            "codeQuality": 93,
            "apiDesign": 82,
            "deployment": 83
        },
        "title": "wedding",
        "description": "使用现代技术构建的全栈应用程序。",
        "longDescription": "使用现代技术构建的全栈应用程序。"
    }
];

export const projects = projectsEn;
